### ISSUE TITLE
Nx Generate UI is disabled 

### ISSUE THREAD

**Issue by Jeybee89** [iguissouma/nx-console-idea-plugin#12]
Nx generate ui is disabled and don't know how to enabled it. 

New project. 
Nx 11.0.20
Angular 11.0.0
Intellij 203.5981.155
nx-console 0.14.0

![Screenshot 2021-01-05 at 18 48 24](https://user-images.githubusercontent.com/29388920/103680809-ff28ad80-4f86-11eb-85c4-dc64fb9cf41f.png)

**Comment by iguissouma** [comment]
Hello,

Sometimes the Nx Generate Ui appear disabled because it's loading the schematics(takes some time for the first time), when you try again it will appear not disabled.

if it's still disabled, for some reasons the loading of schematics fails.
Hard to guess why it's failing without logs.

Do you open the nx monorepo as a project =>  your `nx.json` is on your base project directory and not a subfolder?
Like below:
<img width="457" alt="Screenshot 2021-01-05 at 21 18 14" src="https://user-images.githubusercontent.com/9085108/103694940-09a17200-4f9c-11eb-9d0a-966aa85d9df5.png">

Other feature are working ?
Nx ToolWindow:
<img width="474" alt="Screenshot 2021-01-05 at 21 23 01" src="https://user-images.githubusercontent.com/9085108/103695417-cf84a000-4f9c-11eb-9c98-7595787a2e46.png">

Nx DevTools preferences:
<img width="998" alt="Screenshot 2021-01-05 at 21 24 25" src="https://user-images.githubusercontent.com/9085108/103695430-d6abae00-4f9c-11eb-83c8-be9c05c29a78.png">

Can you attach same pictures of your environment and the idea.log if possible?

**Comment by Jeybee89** [comment]
subfolder was the problem. Thanks for quick help! @iguissouma

**Comment by t-ricci-delta** [comment]
I have a similar issue, but I am opening with Rider a backend solution written C#/.NET, then I attached the frontend folder (nx workspace is outside the backend solution)

**Comment by t-ricci-delta** [comment]
> I have a similar issue, but I am opening with Rider a backend solution written C#/.NET, then I attached the frontend folder (nx workspace is outside the backend solution)

@iguissouma I also configured the Nx DevTools preferences with node interpreter, nx package and nx.json but it doesn't show the loaded/available Nx plugins (in the preferences window) and when trying to create a new file the Nx UI option is disabled.

But the Nx panel showing all the projects tasks on the IDE toolbar is working, it just doesn't have a way to open the Nx generate UI unfortunately

**Comment by iguissouma** [comment]
@t-ricci-delta
In some places of the plugin I look for the `nx.json` in the project base dir. I will try to fix that.
 
If you open the frontend as a new project in a new window so the `nx.json` is in the root folder everything will works as expected.

As a workaround try to open your frontend as a separate project till I find a solution to better handle this case when `nx.json` is not on the root folder of project.
